"""Lazy loading for locally trained IEEE-CIS model artifacts."""
from __future__ import annotations

from functools import lru_cache

from src.models.predict import ArtifactBundle, load_artifacts


@lru_cache(maxsize=1)
def get_bundle() -> ArtifactBundle:
    """Load artifacts generated by ``python -m src.models.train``."""
    return load_artifacts()


def clear_bundle_cache() -> None:
    """Clear the process-local artifact cache (used by tests/reloads)."""
    get_bundle.cache_clear()
